kumuluzee:
  name: model-3d-parser-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  config:
    consul:
      agent: http://52.151.200.181:80
rest-properties:
  maintenance-mode: false
  catalog-service-ip: http://52.142.34.154:8080/v1/models3d
