kumuluzee:
  name: model-3d-parser-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  config:
    consul:
      agent: http://52.151.200.181:80
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                                           <Configuration name="comments">
                                               <Appenders>
                                                   <Console name="console" target="SYSTEM_OUT">
                                                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                                   </Console>
                                                   <Socket name="logstash" host="ad6575dc2-ba70-4490-bf1b-72afa9d875d6-ls.logit.io"
                                                   port="22760" protocol="udp">
                                                       <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                                   </Socket>
                                               </Appenders>
                                               <Loggers>
                                                   <!-- Default logger -->
                                                   <Root level="all">
                                                       <AppenderRef ref="console" level="info" />
                                                       <AppenderRef ref="logstash" level="trace" />
                                                   </Root>
                                               </Loggers>
                                           </Configuration>'
rest-properties:
  maintenance-mode: false
  catalog-service-ip: http://52.142.34.154:8080/v1/models3d
