name: Build with Maven and package as Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Neki prebuild action, ta naj bi bil potreben za dostop do kode
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    # Action ki pove trenutni 훾as
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 1
        format: 'YYYY-MM-DD-HH-mm-ss'

    # Setup za docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        # Specifikacija docker fajla
        file: ./Dockerfile_with_maven_build
        # Ho훾emo da se pusha
        push: true
        # Ime slike z tagom s katerim enoli훾no dolo훾imo sliko (v tem primeru timestamp od prej)
        tags: klemiba/model-3d-catalog:${{ steps.time.outputs.time }}